site_name: Typer
site_description: Typer, create easy to use command line applications. With code easy to write.
site_url: https://typer.tiangolo.com/

theme:
    name: 'material'
    palette:
        primary: 'black'
        accent: 'teal'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: tiangolo/typer
repo_url: https://github.com/tiangolo/typer
edit_uri: ''
google_analytics:
    - 'UA-155009830-1'
    - 'auto'

nav:
    - Typer: 'index.md'
    - Features: 'features.md'
    - Tutorial - User Guide:
        - Tutorial - User Guide - Intro: 'tutorial/intro.md'
        - First Steps: 'tutorial/first-steps.md'
    - Alternatives, Inspiration and Comparisons: 'alternatives.md'
    - Help Typer - Get Help: 'help-typer.md'
    - Development - Contributing: 'contributing.md'
    - Release Notes: release-notes.md

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite
    - extra

extra:
    social:
        - type: 'github'
          link: 'https://github.com/tiangolo/typer'
        - type: 'twitter'
          link: 'https://twitter.com/tiangolo'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/tiangolo'
        - type: 'rss'
          link: 'https://dev.to/tiangolo'
        - type: 'medium'
          link: 'https://medium.com/@tiangolo'
        - type: 'globe'
          link: 'https://tiangolo.com'
